export const SQUEEZE_BREAKOUT_STRATEGY_V1 = {
  id: "squeeze-breakout-v1",
  botProfileId: "squeeze-breakout-100",
  displayName: "$100 Squeeze Breakout Bot",
  version: 1,
  mode: "paper-research",
  cadence: {
    maximumNewEntriesPerDay: 2,
    maximumOpenPositions: 2,
    intendedHoldingDays: [0, 5],
  },
  scanner: {
    id: "paper-squeeze-scanner-v1",
    version: 1,
    cadenceMinutes: 15,
    minimumPriceUsd: 0.08,
    pennyStockMaximumPriceUsd: 5,
    maximumPriceUsd: 50,
    minimumHistoryBars: 45,
    baseLookbackBars: 40,
    dryVolumeRecentBars: 10,
    dryVolumePriorBars: 20,
    maximumBaseRangePct: 20,
    maximumSpreadPct: 1.25,
    minimumAverageDollarVolume: 1_000_000,
    thresholds: {
      observationScore: 40,
      watchlistScore: 65,
      botReviewScore: 80,
    },
  },
  setup: {
    watchScore: 70,
    qualifiedScore: 80,
    readyScore: 85,
    minimumRelativeVolumePace: 1.5,
    readyRelativeVolumePace: 2.0,
    minimumSessionChangePct: 0.5,
    maximumReadySessionChangePct: 12,
    breakoutBufferPct: 0.25,
    maximumChasePct: 5,
  },
  opportunity: {
    partialProfitPct: 15,
    partialFraction: 0.5,
    primaryTargetPct: 25,
    opportunityZonePct: [20, 30],
    trailRemainder: true,
  },
  risk: {
    riskPerTradePct: 1.0,
    maximumPositionAllocationPct: 30,
    maximumOpenRiskPct: 2.0,
    minimumStopPct: 4,
    maximumStopPct: 8,
    defaultStopPct: 5,
    protectWinnerAtPct: 10,
  },
  execution: {
    paperOnly: true,
    executionEnabledByDefault: false,
  },
} as const;

export type SqueezeBreakoutStrategyConfig = typeof SQUEEZE_BREAKOUT_STRATEGY_V1;
