export const THREE_TRADE_SWING_STRATEGY_V1 = {
  id: "three-trade-weekly-swing-v1",
  botProfileId: "three-trade-weekly-swing-100",
  displayName: "$100 Three-Trade Weekly Swing Bot",
  version: 1,
  mode: "paper-only",
  cadence: {
    maximumNewEntriesPerWeek: 3,
    maximumOpenPositions: 3,
    stageExpiry: "same-session",
  },
  setup: {
    fastAveragePeriod: 10,
    slowAveragePeriod: 20,
    momentumLookback: 5,
    breakoutLookback: 20,
    entryBufferPct: 0.10,
    maximumChaseAtr: 0.50,
  },
  risk: {
    riskPerTradePct: 1.00,
    maximumPositionAllocationPct: 30,
    maximumOpenRiskPct: 3.00,
    atrStopMultiplier: 1.75,
    structureLookback: 10,
    structureBufferAtr: 0.10,
    minimumRewardR: 2.00,
    firstTakeProfitR: 2.00,
    firstTakeProfitFraction: 0.50,
    protectWinnerAtR: 1.00,
    trailRemainder: true,
    dailyRealizedLossLimitPct: 2.50,
    weeklyDrawdownLimitPct: 5.00,
    maximumCorrelatedRiskPct: 2.00,
  },
  correlation: {
    groups: {
      QQQ: "us-megacap-tech",
      NVDA: "us-megacap-tech",
      MSFT: "us-megacap-tech",
    },
  },
  selection: {
    simultaneousTriggerPriority: ["QQQ", "NVDA", "MSFT"],
  },
  execution: {
    requiresFreshRevalidation: true,
    submitAtMarketOpen: false,
    minimumMinutesAfterOpen: 5,
    maximumMinutesAfterOpen: 120,
    maximumQuoteAgeSeconds: 30,
    maximumSpreadPct: 0.25,
    allowGapChase: false,
    requireSupportiveBroadMarket: true,
    paperOnly: true,
  },
} as const;
