export const WEEKEND_CRYPTO_DAY_STRATEGY_V1 = {
  id: "weekend-crypto-day-v1",
  botProfileId: "weekend-crypto-day-100",
  displayName: "$100 Weekend Crypto Day Bot",
  version: 1,
  mode: "paper-only",
  timezone: "America/Chicago",
  universe: ["BTC/USD", "ETH/USD", "SOL/USD"],
  session: {
    weekendDays: ["Sat", "Sun"],
    stopNewEntriesLocal: "22:30",
    flatByLocal: "23:45",
  },
  cadence: {
    maximumNewEntriesPerDay: 3,
    maximumOpenPositions: 1,
  },
  marketData: {
    quoteFreshnessSeconds: 60,
    maximumSpreadPct: 0.15,
    fastTimeframeMinutes: 5,
    slowTimeframeMinutes: 15,
    fastBarsRequired: 24,
    slowBarsRequired: 16,
  },
  setup: {
    fastSmaPeriod: 9,
    slowFastSmaPeriod: 4,
    slowSmaPeriod: 12,
    momentumBars: 3,
    breakoutLookbackBars: 6,
    breakoutBufferPct: 0.03,
    maximumChaseAtr: 0.50,
    minimumAtrPct: 0.08,
    maximumAtrPct: 1.50,
    minimumScore: 80,
  },
  risk: {
    riskPerTradePct: 0.50,
    maximumPositionAllocationPct: 30,
    maximumOpenRiskPct: 0.75,
    dailyRealizedLossLimitPct: 1.50,
    minimumStopPct: 0.80,
    maximumStopPct: 2.50,
    atrStopMultiplier: 1.50,
    firstTakeProfitR: 2.00,
    firstTakeProfitFraction: 0.50,
    protectWinnerAtR: 1.00,
    trailRemainder: true,
  },
  fees: {
    estimatedTakerFeeBpsPerSide: 25,
    requiredGrossTargetToRoundTripFeeMultiple: 2.50,
  },
  execution: {
    paperOnly: true,
    executionEnabledByDefault: false,
    oneSymbolPerBrokerAccountAcrossBots: true,
  },
} as const;
