export const CRYPTO_SWING_STRATEGY_V1 = {
  id: "crypto-swing-v1",
  botProfileId: "crypto-swing-100",
  displayName: "$100 Crypto Swing Bot",
  version: 1,
  mode: "paper-research",
  cadence: {
    maximumNewEntriesPerWeek: 3,
    maximumOpenPositions: 2,
    intendedHoldingDays: [1, 7],
  },
  marketData: {
    timeframe: "1Hour",
    lookbackHours: 24 * 14,
    requiredBars: 72,
    maximumQuoteAgeSeconds: 120,
    maximumSpreadPct: 0.75,
  },
  setup: {
    fastAveragePeriod: 12,
    slowAveragePeriod: 48,
    momentumLookbackBars: 12,
    breakoutLookbackBars: 72,
    entryBufferPct: 0.15,
    maximumChaseAtr: 0.75,
    watchScore: 70,
    qualifiedScore: 80,
    readyScore: 85,
  },
  opportunity: {
    minimumGoalProfitPct: 5,
    maximumGoalProfitPct: 20,
    rangeMultiplier: 1.35,
    atrExpansionMultiplier: 6,
    momentumMultiplier: 2.5,
  },
  risk: {
    riskPerTradePct: 1.0,
    maximumPositionAllocationPct: 30,
    maximumOpenRiskPct: 2.0,
    minimumStopPct: 2.0,
    maximumStopPct: 8.0,
    atrStopMultiplier: 2.0,
    protectWinnerAtR: 1.0,
    deRiskAtR: 2.0,
    deRiskFraction: 0.25,
    trailRemainder: true,
  },
  execution: {
    paperOnly: true,
    executionEnabledByDefault: false,
  },
} as const;
