import Link from "next/link";
import metrics from "../../../../research/paper-watchlist/metrics-2026-10-02.json";
import { DEFAULT_PAPER_WATCHLIST } from "@/lib/paper-watchlist";
import styles from "@/components/PaperTradingLab.module.css";

export const metadata = {title:"Paper watchlist history review | CreatorHub"};
const percent = (n: number) => `${n.toFixed(1)}%`;
export default function WatchlistResearch() {
  const selected=[...DEFAULT_PAPER_WATCHLIST.stocks,...DEFAULT_PAPER_WATCHLIST.crypto];
  return <main className={styles.research}>
    <Link href="/paper-trading">← Back to the interactive report</Link>
    <h1>Why these symbols?</h1><p>Historical screening through October 2, 2026 · paper monitoring universe</p>
    <section className={styles.card}><h2>The saved model</h2><p>The $1,000 challenge uses $200 for day trades, $400 for multi-day trades and $400 for multi-week trades. The 9% position cap is $18 / $36 / $36 per respective pool. This is the size of a position, not a maximum loss or stop rule. The actual paper-account balance remains separate.</p><p>The inverse sleeve has zero allocation. SH is monitored only. Crypto shares the same pools and caps. Daily history does not validate intraday entries, and no entry, stop, daily-loss or portfolio-risk rules have been backtested here.</p></section>
    <section className={styles.card}><h2>All 19 candidates are watched</h2><p>All watched assets were active, tradable and fractionable in Alpaca’s asset catalog when reviewed. Account eligibility and order minimums must still be checked at execution time.</p><div className={styles.recordList}>{selected.map(item=><article className={styles.record} key={item.symbol}><h3>{item.symbol} · {item.label}</h3><p>{item.tier === "reserve" ? "Reserve · watched" : "Initial list"} · {item.role} · {item.pools.length ? item.pools.join(" / ")+" research" : "Monitor only · no allocation"}</p><p>{item.rationale}</p><p className={styles.meta}>1-year adjusted-close change {percent(item.return1y)} · annualized daily volatility {percent(item.volatility)} · 1-year maximum close drawdown {percent(item.maxDrawdown)}</p></article>)}</div></section>
    <section className={styles.card}><h2>All candidates reviewed</h2><div className={styles.researchTable}><table><thead><tr><th>Symbol</th><th>1-year change</th><th>Volatility</th><th>Max drawdown</th><th>Watch status</th></tr></thead><tbody>{Object.entries(metrics.metrics).map(([symbol,m])=><tr key={symbol}><td>{symbol.replace("/","-")}</td><td>{percent(m.return365)}</td><td>{percent(m.vol)}</td><td>{percent(m.maxDrawdown)}</td><td>{selected.find(item=>item.symbol===symbol.replace("/","-"))?.tier === "reserve" ? "Reserve · watched" : "Initial list"}</td></tr>)}</tbody></table></div><p>DIA, MSFT, AMZN, GOOGL, META, PSQ and SOL are monitored reserves. They can be evaluated for funded pools when current entry, holding-horizon, liquidity, cost and risk criteria qualify. Initial-list status is a research priority, not an order instruction or a permanent eligibility boundary. Both inverse candidates remain unfunded.</p></section>
    <section className={styles.card}><h2>What the history shows</h2><p>SPY’s reviewed volatility was 13.0%, compared with 37.7% for NVDA, 44.9% for BTC and 63.6% for ETH. Crypto drawdowns exceeded 50%; GLD also had a 26.4% drawdown. QQQ’s 0.93 return correlation with SPY shows considerable overlap. Watching several symbols does not mean they diversify a portfolio.</p><p>Stock data: 503 daily bars per candidate, October 1, 2024–October 2, 2026, Alpaca SIP with all corporate-action adjustments. Crypto: 732 completed UTC daily bars per pair over the same dates. The incomplete October 3 candle is excluded. Calendar 30/90/365-day close changes are calculated; displayed risk metrics use the last year. Volatility uses sample daily returns annualized by 252 stock sessions or 365 crypto days. Drawdown uses closes, so intraday losses can be larger.</p><p>These are descriptive metrics, not strategy returns. They exclude execution costs, taxes, slippage and fees. Crypto venue volume is not treated as consolidated market liquidity. The live watchlist uses IEX stock quotes and Kraken crypto quotes; those feeds differ from the research history.</p><p><a href="https://www.proshares.com/our-etfs/leveraged-and-inverse/sh">SH issuer: daily inverse objective and holding-period effects</a> · <a href="https://docs.alpaca.markets/us/docs/crypto-fees">Alpaca crypto fee schedule</a></p><p>An unfilled candidate may qualify for a different pool; after a fill, its entry-pool attribution stays with that trade. The next trading step is defining risk/entry/exit rules and validating them out of sample with costs. The report places no orders.</p></section>
  </main>;
}
