import Link from "next/link";
import metrics from "../../../../research/paper-watchlist/metrics-2026-10-02.json";
import { DEFAULT_PAPER_WATCHLIST } from "@/lib/paper-watchlist";
import styles from "@/components/PaperTradingLab.module.css";

export const metadata = {title:"Watchlist history review | CreatorHub"};
const percent = (n: number) => `${n.toFixed(1)}%`;
export default function WatchlistResearch() {
  const selected=[...DEFAULT_PAPER_WATCHLIST.stocks,...DEFAULT_PAPER_WATCHLIST.crypto];
  return <main className={styles.research}>
    <Link href="/paper-trading">← Back to the interactive report</Link>
    <h1>Why these symbols?</h1><p>Historical screening through October 2, 2026 · virtual monitoring universe</p>
    <section className={styles.card}><h2>The saved model</h2><p>Every bot challenge starts at $100. Default Diverse reserves up to 20% / 40% / 40% of virtual equity for day / multi-day / multi-week exposure. Those are portfolio allocation ceilings, not fixed position sizes. Individual position size comes from the strategy risk engine. External execution infrastructure remains separate from the virtual fund and is not strategy capital.</p><p>The inverse sleeve has zero allocation. SH is monitored only. Crypto shares the same pool ceilings. Daily history does not validate intraday entries; execution still requires the live strategy score, stop calculation, risk state, and available pool capacity.</p></section>
    <section className={styles.card}><h2>All 19 candidates are watched</h2><p>All watched assets were active, tradable and fractionable in the configured market catalog when reviewed. Account eligibility and order minimums must still be checked at execution time.</p><div className={styles.recordList}>{selected.map(item=><article className={styles.record} key={item.symbol}><h3>{item.symbol} · {item.label}</h3><p>{item.tier === "reserve" ? "Reserve · watched" : "Initial list"} · {item.role} · {item.pools.length ? item.pools.join(" / ")+" research" : "Monitor only · no allocation"}</p><p>{item.rationale}</p><p className={styles.meta}>1-year adjusted-close change {percent(item.return1y)} · annualized daily volatility {percent(item.volatility)} · 1-year maximum close drawdown {percent(item.maxDrawdown)}</p></article>)}</div></section>
    <section className={styles.card}><h2>All candidates reviewed</h2><div className={styles.researchTable}><table><thead><tr><th>Symbol</th><th>1-year change</th><th>Volatility</th><th>Max drawdown</th><th>Watch status</th></tr></thead><tbody>{Object.entries(metrics.metrics).map(([symbol,m])=><tr key={symbol}><td>{symbol.replace("/","-")}</td><td>{percent(m.return365)}</td><td>{percent(m.vol)}</td><td>{percent(m.maxDrawdown)}</td><td>{selected.find(item=>item.symbol===symbol.replace("/","-"))?.tier === "reserve" ? "Reserve · watched" : "Initial list"}</td></tr>)}</tbody></table></div><p>DIA, MSFT, AMZN, GOOGL, META, PSQ and SOL are monitored reserves. They can be evaluated for funded pools when current entry, holding-horizon, liquidity, cost and risk criteria qualify. Initial-list status is a research priority, not an order instruction or a permanent eligibility boundary. Both inverse candidates remain unfunded.</p></section>
    <section className={styles.card}><h2>What the history shows</h2><p>SPY’s reviewed volatility was 13.0%, compared with 37.7% for NVDA, 44.9% for BTC and 63.6% for ETH. Crypto drawdowns exceeded 50%; GLD also had a 26.4% drawdown. QQQ’s 0.93 return correlation with SPY shows considerable overlap. Watching several symbols does not mean they diversify a portfolio.</p><p>Stock data: 503 adjusted daily bars per candidate, October 1, 2024–October 2, 2026, from the configured historical market-data feed. Crypto: 732 completed UTC daily bars per pair over the same dates. The incomplete October 3 candle is excluded. Calendar 30/90/365-day close changes are calculated; displayed risk metrics use the last year. Volatility uses sample daily returns annualized by 252 stock sessions or 365 crypto days. Drawdown uses closes, so intraday losses can be larger.</p><p>These are descriptive metrics, not strategy returns. They exclude execution costs, taxes, slippage and fees. Crypto venue volume is not treated as consolidated market liquidity. The live watchlist uses configured stock and crypto quote feeds; those feeds may differ from the research-history source.</p><p><a href="https://www.proshares.com/our-etfs/leveraged-and-inverse/sh">SH issuer: daily inverse objective and holding-period effects</a> · Crypto execution assumptions use the configured simulation fee model.</p><p>An unfilled candidate may qualify for a different pool; after a fill, its entry-pool attribution stays with that trade. The next trading step is defining risk/entry/exit rules and validating them out of sample with costs. The report places no orders.</p></section>
  </main>;
}
