-- Market Mover Intelligence v1: append-only evidence observations.
-- Scores are provisional, attribution is explicitly unknown, and nothing grants trade authority.
create table if not exists public.paper_market_mover_observations (
  id bigint generated by default as identity primary key,
  asset_class text not null check (asset_class in ('stock','crypto')),
  symbol text not null check (char_length(symbol) between 1 and 24),
  signal_kind text not null check (signal_kind in ('stock-large-print','crypto-book-depth')),
  observed_bucket timestamptz not null,
  event_at timestamptz not null,
  available_at timestamptz not null,
  observed_at timestamptz not null default now(),
  score numeric(5,2) not null check (score between 0 and 100),
  confidence numeric(5,2) not null check (confidence between 0 and 100),
  direction text not null check (direction in ('buy-side-depth','sell-side-depth','balanced-depth','unknown')),
  actor_class text not null default 'unattributed' check (actor_class = 'unattributed'),
  source_name text not null,
  evidence jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint paper_market_mover_unique_sample unique (asset_class,symbol,signal_kind,observed_bucket),
  constraint paper_market_mover_knowledge_after_event check (available_at >= event_at),
  constraint paper_market_mover_observation_after_knowledge check (observed_at >= available_at)
);

create index if not exists paper_market_mover_recent_idx
  on public.paper_market_mover_observations (observed_at desc, score desc);
create index if not exists paper_market_mover_symbol_idx
  on public.paper_market_mover_observations (asset_class,symbol,observed_at desc);
alter table public.paper_market_mover_observations enable row level security;
revoke all on public.paper_market_mover_observations from anon, authenticated;
grant all on public.paper_market_mover_observations to service_role;
comment on table public.paper_market_mover_observations is
  'Research-only, timestamped, single-venue, unattributed market activity. Never an execution permission or confirmed institutional purchase.';
