create table if not exists public.paper_squeeze_prospects (
  symbol text primary key,
  scanner_id text not null,
  scanner_version integer not null check (scanner_version > 0),
  status text not null check (status in ('candidate','watchlist','review-ready','expired')),
  score numeric(8,2) not null check (score >= 0 and score <= 100),
  price numeric(28,10),
  previous_close numeric(28,10),
  spread_pct numeric(18,6),
  current_volume numeric(28,8),
  base_days integer,
  base_high numeric(28,10),
  base_low numeric(28,10),
  base_range_pct numeric(18,6),
  pre_ignition_position_pct numeric(18,6),
  volume_dry_ratio numeric(18,6),
  relative_volume_pace numeric(18,6),
  breakout_distance_pct numeric(18,6),
  session_change_pct numeric(18,6),
  average_dollar_volume numeric(28,8),
  watchlist_eligible boolean not null default false,
  bot_review_eligible boolean not null default false,
  score_components jsonb not null default '{}'::jsonb,
  reasons jsonb not null default '[]'::jsonb,
  source_updated_at timestamptz,
  first_seen_at timestamptz not null default now(),
  first_watchlist_at timestamptz,
  first_review_ready_at timestamptz,
  last_seen_at timestamptz not null default now(),
  last_scanned_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb
);

create table if not exists public.paper_squeeze_observations (
  id bigint generated by default as identity primary key,
  scanned_at timestamptz not null,
  scanner_id text not null,
  scanner_version integer not null check (scanner_version > 0),
  symbol text not null,
  status text not null check (status in ('candidate','watchlist','review-ready')),
  score numeric(8,2) not null check (score >= 0 and score <= 100),
  price numeric(28,10),
  spread_pct numeric(18,6),
  current_volume numeric(28,8),
  base_days integer,
  base_high numeric(28,10),
  base_low numeric(28,10),
  base_range_pct numeric(18,6),
  pre_ignition_position_pct numeric(18,6),
  volume_dry_ratio numeric(18,6),
  relative_volume_pace numeric(18,6),
  breakout_distance_pct numeric(18,6),
  session_change_pct numeric(18,6),
  average_dollar_volume numeric(28,8),
  watchlist_eligible boolean not null,
  bot_review_eligible boolean not null,
  score_components jsonb not null default '{}'::jsonb,
  reasons jsonb not null default '[]'::jsonb,
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists paper_squeeze_prospects_score_idx
  on public.paper_squeeze_prospects(status,score desc,last_seen_at desc);
create index if not exists paper_squeeze_observations_symbol_idx
  on public.paper_squeeze_observations(symbol,scanned_at desc);
create index if not exists paper_squeeze_observations_scan_idx
  on public.paper_squeeze_observations(scanned_at desc,score desc);

create or replace function public.paper_squeeze_preserve_timestamps()
returns trigger
language plpgsql
security invoker
set search_path=''
as $$
begin
  if tg_op='UPDATE' then
    new.first_seen_at := old.first_seen_at;
    if old.watchlist_eligible and new.first_watchlist_at is null then
      new.first_watchlist_at := old.first_watchlist_at;
    elsif not old.watchlist_eligible and new.watchlist_eligible and new.first_watchlist_at is null then
      new.first_watchlist_at := now();
    end if;
    if old.bot_review_eligible and new.first_review_ready_at is null then
      new.first_review_ready_at := old.first_review_ready_at;
    elsif not old.bot_review_eligible and new.bot_review_eligible and new.first_review_ready_at is null then
      new.first_review_ready_at := now();
    end if;
  else
    if new.watchlist_eligible and new.first_watchlist_at is null then new.first_watchlist_at := now(); end if;
    if new.bot_review_eligible and new.first_review_ready_at is null then new.first_review_ready_at := now(); end if;
  end if;
  return new;
end $$;

drop trigger if exists paper_squeeze_preserve_timestamps on public.paper_squeeze_prospects;
create trigger paper_squeeze_preserve_timestamps
before insert or update on public.paper_squeeze_prospects
for each row execute function public.paper_squeeze_preserve_timestamps();

create or replace function public.paper_expire_stale_squeeze_prospects(p_now timestamptz)
returns integer
language plpgsql
security invoker
set search_path=''
as $$
declare
  v_count integer := 0;
begin
  update public.paper_squeeze_prospects
  set status='expired',
      watchlist_eligible=false,
      bot_review_eligible=false,
      last_scanned_at=p_now
  where status <> 'expired'
    and last_seen_at < p_now - interval '48 hours';
  get diagnostics v_count = row_count;
  return v_count;
end $$;

alter table public.paper_squeeze_prospects enable row level security;
alter table public.paper_squeeze_observations enable row level security;

revoke all on table public.paper_squeeze_prospects from public,anon,authenticated;
revoke all on table public.paper_squeeze_observations from public,anon,authenticated;
grant select,insert,update,delete on table public.paper_squeeze_prospects to service_role;
grant select,insert,update,delete on table public.paper_squeeze_observations to service_role;
grant usage,select on sequence public.paper_squeeze_observations_id_seq to service_role;
revoke all on function public.paper_squeeze_preserve_timestamps() from public,anon,authenticated;
grant execute on function public.paper_squeeze_preserve_timestamps() to service_role;
revoke all on function public.paper_expire_stale_squeeze_prospects(timestamptz) from public,anon,authenticated;
grant execute on function public.paper_expire_stale_squeeze_prospects(timestamptz) to service_role;

insert into public.paper_bot_ledgers(
  bot_id,display_name,status,strategy_id,strategy_version,
  starting_cash,cash,equity,realized_pl,unrealized_pl,buying_power,
  peak_equity,current_drawdown_pct,open_planned_risk_pct,
  correlated_risk_pct,daily_realized_loss_pct,weekly_drawdown_pct,
  source,broker_tag,metadata
) values (
  'squeeze-breakout-100',
  '$100 Squeeze Breakout Bot',
  'active',
  'squeeze-breakout-v1',
  1,
  100,100,100,0,0,100,
  100,0,0,0,0,0,
  'virtual',
  'sqz',
  '{
    "challenge":"$100 base-compression and volume-ignition squeeze breakout research bot",
    "executionVenue":"alpaca-paper",
    "executionEnabled":false,
    "executionMode":"paper-squeeze-breakout",
    "liveMoneyEnabled":false,
    "maxNewTradesPerDay":2,
    "maxOpenPositions":2,
    "intendedHoldingDays":[0,5],
    "targetOpportunityZonePct":[20,30],
    "primaryTargetPct":25,
    "partialProfitPct":15,
    "partialFraction":0.5,
    "squeezeScannerRequired":true,
    "challengeStartingCash":100,
    "tradeAttributionRequired":true,
    "brokerAccountEquityIsNotBotEquity":true,
    "brokerAccountIsExecutionVenueOnly":true
  }'::jsonb
)
on conflict (bot_id) do update set
  display_name=excluded.display_name,
  status=excluded.status,
  strategy_id=excluded.strategy_id,
  strategy_version=excluded.strategy_version,
  broker_tag=excluded.broker_tag,
  metadata=public.paper_bot_ledgers.metadata || excluded.metadata,
  updated_at=now();

insert into public.paper_bot_equity_history(
  bot_id,bucket_minute,collected_at,equity,cash,realized_pl,unrealized_pl
)
select bot_id,date_trunc('minute',now()),now(),equity,cash,realized_pl,unrealized_pl
from public.paper_bot_ledgers
where bot_id='squeeze-breakout-100'
on conflict (bot_id,bucket_minute) do update
set collected_at=excluded.collected_at,
    equity=excluded.equity,
    cash=excluded.cash,
    realized_pl=excluded.realized_pl,
    unrealized_pl=excluded.unrealized_pl;

update public.paper_capital_plan
set reserved_bot_pools=6,
    allocated_capital=600,
    unallocated_reserve=400,
    metadata=metadata || jsonb_build_object(
      'description','Six $100 bot pools reserved now; remaining $400 held for future bot pools.',
      'squeezeBreakoutPoolReserved',true
    ),
    updated_at=now()
where plan_id='main';

update public.paper_bot_ledgers
set metadata=metadata || jsonb_build_object(
  'capitalPlanId','main',
  'capitalPoolUsd',100,
  'capitalPoolReserved',true,
  'capitalPoolIndex',6,
  'programCapitalUsd',1000
),
updated_at=now()
where bot_id='squeeze-breakout-100';
