create table if not exists public.paper_prospects (
  asset_class text not null check (asset_class in ('stock','crypto')),
  symbol text not null,
  scanner_id text not null,
  scanner_version integer not null check (scanner_version > 0),
  status text not null check (status in ('candidate','watchlist','review-ready','expired')),
  score numeric(8,2) not null check (score >= 0 and score <= 100),
  price numeric(28,10),
  percent_change numeric(18,6),
  spread_pct numeric(18,6),
  volume numeric(28,8),
  previous_volume numeric(28,8),
  volume_ratio numeric(18,6),
  activity_rank integer,
  near_high_pct numeric(18,6),
  watchlist_eligible boolean not null default false,
  bot_review_eligible boolean not null default false,
  suggested_bot_ids text[] not null default '{}'::text[],
  assigned_bot_ids text[] not null default '{}'::text[],
  score_components jsonb not null default '{}'::jsonb,
  reasons jsonb not null default '[]'::jsonb,
  source_flags jsonb not null default '[]'::jsonb,
  source_updated_at timestamptz,
  first_seen_at timestamptz not null default now(),
  first_watchlist_at timestamptz,
  first_review_ready_at timestamptz,
  last_seen_at timestamptz not null default now(),
  last_scanned_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb,
  primary key (asset_class,symbol)
);

create table if not exists public.paper_prospect_observations (
  id bigint generated by default as identity primary key,
  scanned_at timestamptz not null,
  scanner_id text not null,
  scanner_version integer not null check (scanner_version > 0),
  asset_class text not null check (asset_class in ('stock','crypto')),
  symbol text not null,
  status text not null check (status in ('candidate','watchlist','review-ready')),
  score numeric(8,2) not null check (score >= 0 and score <= 100),
  price numeric(28,10),
  percent_change numeric(18,6),
  spread_pct numeric(18,6),
  volume numeric(28,8),
  volume_ratio numeric(18,6),
  activity_rank integer,
  near_high_pct numeric(18,6),
  watchlist_eligible boolean not null,
  bot_review_eligible boolean not null,
  suggested_bot_ids text[] not null default '{}'::text[],
  score_components jsonb not null default '{}'::jsonb,
  reasons jsonb not null default '[]'::jsonb,
  source_flags jsonb not null default '[]'::jsonb,
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists paper_prospects_score_idx
  on public.paper_prospects(status,score desc,last_seen_at desc);
create index if not exists paper_prospect_observations_symbol_idx
  on public.paper_prospect_observations(asset_class,symbol,scanned_at desc);
create index if not exists paper_prospect_observations_scan_idx
  on public.paper_prospect_observations(scanned_at desc,score desc);

create or replace function public.paper_prospect_preserve_timestamps()
returns trigger
language plpgsql
security invoker
set search_path=''
as $$
begin
  if tg_op='UPDATE' then
    new.first_seen_at := old.first_seen_at;
    if old.watchlist_eligible and new.first_watchlist_at is null then
      new.first_watchlist_at := old.first_watchlist_at;
    elsif not old.watchlist_eligible and new.watchlist_eligible and new.first_watchlist_at is null then
      new.first_watchlist_at := now();
    end if;
    if old.bot_review_eligible and new.first_review_ready_at is null then
      new.first_review_ready_at := old.first_review_ready_at;
    elsif not old.bot_review_eligible and new.bot_review_eligible and new.first_review_ready_at is null then
      new.first_review_ready_at := now();
    end if;
    new.assigned_bot_ids := old.assigned_bot_ids;
  else
    if new.watchlist_eligible and new.first_watchlist_at is null then new.first_watchlist_at := now(); end if;
    if new.bot_review_eligible and new.first_review_ready_at is null then new.first_review_ready_at := now(); end if;
  end if;
  return new;
end $$;

drop trigger if exists paper_prospect_preserve_timestamps on public.paper_prospects;
create trigger paper_prospect_preserve_timestamps
before insert or update on public.paper_prospects
for each row execute function public.paper_prospect_preserve_timestamps();

create or replace function public.paper_expire_stale_prospects(p_now timestamptz)
returns integer
language plpgsql
security invoker
set search_path=''
as $$
declare
  v_count integer := 0;
begin
  update public.paper_prospects
  set status='expired',
      watchlist_eligible=false,
      bot_review_eligible=false,
      suggested_bot_ids='{}'::text[],
      last_scanned_at=p_now
  where status <> 'expired'
    and (
      (asset_class='crypto' and last_seen_at < p_now - interval '2 hours')
      or
      (asset_class='stock' and last_seen_at < p_now - interval '36 hours')
    );
  get diagnostics v_count = row_count;
  return v_count;
end $$;

alter table public.paper_prospects enable row level security;
alter table public.paper_prospect_observations enable row level security;

revoke all on table public.paper_prospects from public,anon,authenticated;
revoke all on table public.paper_prospect_observations from public,anon,authenticated;
grant all on table public.paper_prospects to service_role;
grant all on table public.paper_prospect_observations to service_role;
grant usage,select on sequence public.paper_prospect_observations_id_seq to service_role;
revoke all on function public.paper_prospect_preserve_timestamps() from public,anon,authenticated;
grant execute on function public.paper_prospect_preserve_timestamps() to service_role;
revoke all on function public.paper_expire_stale_prospects(timestamptz) from public,anon,authenticated;
grant execute on function public.paper_expire_stale_prospects(timestamptz) to service_role;
