create table if not exists public.paper_bot_trade_metrics (
  id bigint generated by default as identity primary key,
  bot_id text not null,
  strategy_id text,
  strategy_version integer,
  symbol text not null,
  asset_class text not null default 'unknown',
  status text not null default 'open' check (status in ('open','closing','closed')),
  opened_at timestamptz not null,
  closed_at timestamptz,
  entry_price numeric,
  initial_protective_stop numeric,
  initial_risk_dollars numeric,
  peak_mark_price numeric,
  trough_mark_price numeric,
  last_mark_price numeric,
  last_mark_at timestamptz,
  mark_count integer not null default 0 check (mark_count >= 0),
  mfe_r numeric not null default 0,
  mae_r numeric not null default 0,
  exit_price numeric,
  realized_pl numeric,
  r_multiple numeric,
  estimated_fees numeric,
  exit_reason text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.paper_bot_trade_metrics enable row level security;
revoke all on table public.paper_bot_trade_metrics from public, anon, authenticated;
grant select, insert, update, delete on table public.paper_bot_trade_metrics to service_role;
grant usage, select on all sequences in schema public to service_role;

create unique index if not exists paper_bot_trade_metrics_active_idx
  on public.paper_bot_trade_metrics(bot_id, symbol)
  where status in ('open','closing');

create index if not exists paper_bot_trade_metrics_closed_idx
  on public.paper_bot_trade_metrics(bot_id, closed_at desc)
  where status='closed';

create or replace function public.paper_bot_capture_trade_metrics()
returns trigger
language plpgsql
security invoker
set search_path=''
as $$
declare
  v_id bigint;
  v_entry numeric;
  v_stop numeric;
  v_risk_distance numeric;
  v_mark numeric;
  v_mark_at timestamptz;
  v_excursion_r numeric;
begin
  if tg_op='DELETE' then
    update public.paper_bot_trade_metrics
    set status='closing',
        metadata=metadata||jsonb_build_object(
          'positionDeletedAt',now(),
          'lastPositionQuantity',old.quantity,
          'lastPositionAverageEntry',old.average_entry
        ),
        updated_at=now()
    where bot_id=old.bot_id and symbol=old.symbol and status='open';
    return old;
  end if;

  v_entry:=new.average_entry;
  v_stop:=coalesce(new.initial_protective_stop,new.protective_stop);
  v_mark:=nullif(new.metadata->>'markPrice','')::numeric;
  v_mark_at:=nullif(new.metadata->>'markAt','')::timestamptz;
  v_risk_distance:=case when v_entry is not null and v_stop is not null and v_stop<v_entry
    then v_entry-v_stop else null end;

  select id into v_id
  from public.paper_bot_trade_metrics
  where bot_id=new.bot_id and symbol=new.symbol and status in ('open','closing')
  order by id desc
  limit 1
  for update;

  if v_id is null then
    insert into public.paper_bot_trade_metrics(
      bot_id,strategy_id,strategy_version,symbol,asset_class,status,opened_at,
      entry_price,initial_protective_stop,initial_risk_dollars,
      peak_mark_price,trough_mark_price,last_mark_price,last_mark_at,mark_count,mfe_r,mae_r,metadata
    ) values (
      new.bot_id,new.strategy_id,new.strategy_version,new.symbol,new.asset_class,'open',
      coalesce(new.opened_at,now()),
      v_entry,v_stop,new.planned_risk_dollars,
      coalesce(v_mark,v_entry),coalesce(v_mark,v_entry),v_mark,v_mark_at,
      case when v_mark is not null and v_mark_at is not null then 1 else 0 end,
      case when v_risk_distance>0 and v_mark is not null then greatest(0,(v_mark-v_entry)/v_risk_distance) else 0 end,
      case when v_risk_distance>0 and v_mark is not null then least(0,(v_mark-v_entry)/v_risk_distance) else 0 end,
      jsonb_build_object('source','paper-bot-position-trigger')
    )
    returning id into v_id;
  else
    update public.paper_bot_trade_metrics
    set strategy_id=coalesce(new.strategy_id,strategy_id),
        strategy_version=coalesce(new.strategy_version,strategy_version),
        asset_class=new.asset_class,
        status='open',
        entry_price=coalesce(v_entry,entry_price),
        initial_protective_stop=coalesce(v_stop,initial_protective_stop),
        initial_risk_dollars=coalesce(new.planned_risk_dollars,initial_risk_dollars),
        updated_at=now()
    where id=v_id;
  end if;

  if v_mark is not null and v_mark>0 and v_mark_at is not null then
    if v_risk_distance is not null and v_risk_distance>0 then
      v_excursion_r:=(v_mark-v_entry)/v_risk_distance;
    else
      v_excursion_r:=null;
    end if;

    update public.paper_bot_trade_metrics
    set peak_mark_price=greatest(coalesce(peak_mark_price,v_mark),v_mark),
        trough_mark_price=least(coalesce(trough_mark_price,v_mark),v_mark),
        last_mark_price=v_mark,
        last_mark_at=v_mark_at,
        mark_count=mark_count + case when last_mark_at is distinct from v_mark_at then 1 else 0 end,
        mfe_r=case when v_excursion_r is null then mfe_r else greatest(mfe_r,v_excursion_r,0) end,
        mae_r=case when v_excursion_r is null then mae_r else least(mae_r,v_excursion_r,0) end,
        metadata=metadata||jsonb_build_object('lastMarkSource',coalesce(new.metadata->>'markSource','unknown')),
        updated_at=now()
    where id=v_id;
  end if;

  return new;
end $$;

revoke all on function public.paper_bot_capture_trade_metrics() from public,anon,authenticated;
grant execute on function public.paper_bot_capture_trade_metrics() to service_role;

drop trigger if exists paper_bot_trade_metrics_capture on public.paper_bot_positions;
create trigger paper_bot_trade_metrics_capture
after insert or update or delete on public.paper_bot_positions
for each row execute function public.paper_bot_capture_trade_metrics();

create or replace function public.paper_bot_finalize_trade_metrics(p_collected_at timestamptz)
returns jsonb
language plpgsql
security invoker
set search_path=''
as $$
declare
  v_trade record;
  v_closed_at timestamptz;
  v_exit_price numeric;
  v_exit_qty numeric;
  v_realized numeric;
  v_fees numeric;
  v_r numeric;
  v_reason text;
  v_entry_client text;
  v_exit_client text;
  v_count integer:=0;
begin
  if p_collected_at is null then raise exception 'Trade finalization timestamp is required'; end if;

  for v_trade in
    select *
    from public.paper_bot_trade_metrics
    where status='closing'
    order by id
    for update
  loop
    select
      max(j.occurred_at),
      case when sum(coalesce(j.quantity,0))>0
        then sum(coalesce(j.exit_price,0)*coalesce(j.quantity,0))/sum(coalesce(j.quantity,0))
        else null end,
      sum(coalesce(j.quantity,0)),
      sum(coalesce(j.realized_pl,0))
    into v_closed_at,v_exit_price,v_exit_qty,v_realized
    from public.paper_bot_journal j
    where j.bot_id=v_trade.bot_id
      and j.symbol=v_trade.symbol
      and j.event_type='filled'
      and j.exit_price is not null
      and j.occurred_at>=v_trade.opened_at;

    if v_closed_at is null then continue; end if;

    select coalesce(sum(
      greatest(0,coalesce(nullif(j.metadata->>'estimatedFeeValueUsd','')::numeric,0))
    ),0)
    into v_fees
    from public.paper_bot_journal j
    where j.bot_id=v_trade.bot_id
      and j.symbol=v_trade.symbol
      and j.event_type='filled'
      and j.occurred_at>=v_trade.opened_at
      and j.occurred_at<=v_closed_at;

    select j.client_order_id into v_entry_client
    from public.paper_bot_journal j
    where j.bot_id=v_trade.bot_id
      and j.symbol=v_trade.symbol
      and j.event_type='filled'
      and j.entry_price is not null
      and j.occurred_at>=v_trade.opened_at
    order by j.occurred_at asc,j.id asc
    limit 1;

    select
      j.client_order_id,
      coalesce(nullif(o.metadata->>'purpose',''),nullif(o.stage_reason,''),'broker-sell')
    into v_exit_client,v_reason
    from public.paper_bot_journal j
    left join public.paper_bot_orders o
      on o.bot_id=j.bot_id and o.client_order_id=j.client_order_id
    where j.bot_id=v_trade.bot_id
      and j.symbol=v_trade.symbol
      and j.event_type='filled'
      and j.exit_price is not null
      and j.occurred_at>=v_trade.opened_at
    order by j.occurred_at desc,j.id desc
    limit 1;

    v_r:=case when v_trade.initial_risk_dollars is not null and v_trade.initial_risk_dollars>0
      then v_realized/v_trade.initial_risk_dollars else null end;

    update public.paper_bot_trade_metrics
    set status='closed',
        closed_at=v_closed_at,
        exit_price=v_exit_price,
        realized_pl=v_realized,
        r_multiple=v_r,
        estimated_fees=v_fees,
        exit_reason=coalesce(v_reason,'broker-sell'),
        metadata=metadata||jsonb_build_object(
          'finalizedAt',p_collected_at,
          'exitQuantity',v_exit_qty,
          'entryClientOrderId',v_entry_client,
          'exitClientOrderId',v_exit_client,
          'durationSeconds',extract(epoch from (v_closed_at-v_trade.opened_at))
        ),
        updated_at=now()
    where id=v_trade.id;

    if not exists (
      select 1 from public.paper_bot_journal
      where event_type='closed'
        and metadata->>'tradeMetricsId'=v_trade.id::text
    ) then
      insert into public.paper_bot_journal(
        bot_id,strategy_id,strategy_version,event_type,symbol,asset_class,occurred_at,
        client_order_id,entry_price,exit_price,quantity,realized_pl,r_multiple,mfe_r,mae_r,exit_reason,metadata
      ) values (
        v_trade.bot_id,v_trade.strategy_id,v_trade.strategy_version,'closed',v_trade.symbol,v_trade.asset_class,v_closed_at,
        v_entry_client,v_trade.entry_price,v_exit_price,v_exit_qty,v_realized,v_r,v_trade.mfe_r,v_trade.mae_r,
        coalesce(v_reason,'broker-sell'),
        jsonb_build_object(
          'tradeMetricsId',v_trade.id,
          'estimatedFeesUsd',v_fees,
          'peakMarkPrice',v_trade.peak_mark_price,
          'troughMarkPrice',v_trade.trough_mark_price,
          'markCount',v_trade.mark_count,
          'openedAt',v_trade.opened_at,
          'closedAt',v_closed_at,
          'exitClientOrderId',v_exit_client
        )
      );
    end if;

    v_count:=v_count+1;
  end loop;

  return jsonb_build_object('tradesFinalized',v_count);
end $$;

revoke all on function public.paper_bot_finalize_trade_metrics(timestamptz)
from public,anon,authenticated;
grant execute on function public.paper_bot_finalize_trade_metrics(timestamptz)
to service_role;
