create table if not exists public.paper_bot_counterfactuals (
  id bigint generated by default as identity primary key,
  setup_key text not null unique,
  bot_id text not null references public.paper_bot_ledgers(bot_id) on delete cascade,
  strategy_id text,
  strategy_version integer check (strategy_version is null or strategy_version > 0),
  symbol text not null check (char_length(symbol) between 1 and 32),
  asset_class text not null default 'unknown' check (asset_class in ('stock','etf','crypto','unknown')),
  source_event_type text not null check (source_event_type in ('candidate','rejected','canceled','expired','replaced','execution_error','authorized')),
  decision_state text,
  decision_at timestamptz not null,
  session_key text,
  status text not null default 'watching'
    check (status in ('watching','triggered','completed','expired','ambiguous','superseded')),
  score numeric(8,3),
  trigger_price numeric(28,10) not null check (trigger_price > 0),
  max_entry_price numeric(28,10) not null check (max_entry_price > 0),
  protective_stop numeric(28,10) not null check (protective_stop > 0),
  planned_take_profit numeric(28,10),
  assumed_entry_price numeric(28,10),
  risk_per_unit numeric(28,10),
  one_r_price numeric(28,10),
  two_r_price numeric(28,10),
  triggered_at timestamptz,
  stop_hit_at timestamptz,
  one_r_hit_at timestamptz,
  two_r_hit_at timestamptz,
  first_outcome text,
  peak_price numeric(28,10),
  trough_price numeric(28,10),
  last_bar_at timestamptz,
  mark_count integer not null default 0 check (mark_count >= 0),
  mfe_r numeric(14,6) not null default 0,
  mae_r numeric(14,6) not null default 0,
  blockers jsonb not null default '[]'::jsonb check (jsonb_typeof(blockers)='array'),
  warnings jsonb not null default '[]'::jsonb check (jsonb_typeof(warnings)='array'),
  metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(metadata)='object'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists paper_bot_counterfactuals_active_idx
  on public.paper_bot_counterfactuals(bot_id,status,decision_at desc)
  where status in ('watching','triggered');

create index if not exists paper_bot_counterfactuals_symbol_idx
  on public.paper_bot_counterfactuals(bot_id,symbol,decision_at desc);

create index if not exists paper_bot_counterfactuals_outcome_idx
  on public.paper_bot_counterfactuals(bot_id,first_outcome,decision_at desc)
  where first_outcome is not null;

alter table public.paper_bot_counterfactuals enable row level security;
revoke all on table public.paper_bot_counterfactuals from public,anon,authenticated;
grant select,insert,update,delete on table public.paper_bot_counterfactuals to service_role;
grant usage,select on sequence public.paper_bot_counterfactuals_id_seq to service_role;
