create table public.paper_bot_ledgers (
  bot_id text primary key check (bot_id ~ '^[a-z0-9][a-z0-9-]{1,63}$'),
  display_name text not null check (char_length(display_name) between 1 and 120),
  status text not null check (status in ('active','planned','paused')),
  strategy_id text,
  strategy_version integer check (strategy_version is null or strategy_version > 0),
  starting_cash numeric(18,6) not null check (starting_cash > 0),
  cash numeric(18,6) not null,
  equity numeric(18,6) not null check (equity >= 0),
  realized_pl numeric(18,6) not null default 0,
  unrealized_pl numeric(18,6) not null default 0,
  buying_power numeric(18,6),
  peak_equity numeric(18,6) not null check (peak_equity >= 0),
  current_drawdown_pct numeric(10,6) not null default 0 check (current_drawdown_pct <= 0),
  open_planned_risk_pct numeric(10,6),
  correlated_risk_pct numeric(10,6),
  daily_realized_loss_pct numeric(10,6),
  weekly_drawdown_pct numeric(10,6),
  last_synced_at timestamptz,
  source text not null default 'virtual',
  metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(metadata) = 'object'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.paper_bot_equity_history (
  bot_id text not null references public.paper_bot_ledgers(bot_id) on delete cascade,
  bucket_minute timestamptz not null,
  collected_at timestamptz not null,
  equity numeric(18,6) not null check (equity >= 0),
  cash numeric(18,6),
  realized_pl numeric(18,6),
  unrealized_pl numeric(18,6),
  primary key (bot_id, bucket_minute)
);

create table public.paper_bot_positions (
  bot_id text not null references public.paper_bot_ledgers(bot_id) on delete cascade,
  symbol text not null check (char_length(symbol) between 1 and 32),
  asset_class text not null default 'unknown' check (asset_class in ('stock','etf','crypto','unknown')),
  side text not null default 'long' check (side in ('long','short')),
  quantity numeric(28,10) not null,
  average_entry numeric(28,10),
  market_value numeric(18,6),
  unrealized_pl numeric(18,6),
  protective_stop numeric(28,10),
  planned_risk_dollars numeric(18,6),
  planned_risk_pct numeric(10,6),
  strategy_id text,
  strategy_version integer,
  opened_at timestamptz,
  updated_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(metadata) = 'object'),
  primary key (bot_id, symbol)
);

create table public.paper_bot_journal (
  id bigint generated by default as identity primary key,
  bot_id text not null references public.paper_bot_ledgers(bot_id) on delete cascade,
  strategy_id text,
  strategy_version integer check (strategy_version is null or strategy_version > 0),
  event_type text not null check (event_type in ('candidate','rejected','authorized','submitted','filled','position_update','stop_update','partial_exit','closed','risk_event','system')),
  symbol text check (symbol is null or char_length(symbol) between 1 and 32),
  asset_class text check (asset_class is null or asset_class in ('stock','etf','crypto','unknown')),
  occurred_at timestamptz not null default now(),
  score numeric(7,3),
  qualification text check (qualification is null or qualification in ('unqualified','watch','qualified','trade-ready')),
  regime text check (regime is null or regime in ('bullish','neutral','bearish','unknown')),
  component_scores jsonb not null default '{}'::jsonb check (jsonb_typeof(component_scores) = 'object'),
  market_snapshot jsonb not null default '{}'::jsonb check (jsonb_typeof(market_snapshot) = 'object'),
  risk_plan jsonb not null default '{}'::jsonb check (jsonb_typeof(risk_plan) = 'object'),
  blockers jsonb not null default '[]'::jsonb check (jsonb_typeof(blockers) = 'array'),
  warnings jsonb not null default '[]'::jsonb check (jsonb_typeof(warnings) = 'array'),
  broker_order_id text,
  client_order_id text,
  entry_price numeric(28,10),
  exit_price numeric(28,10),
  quantity numeric(28,10),
  realized_pl numeric(18,6),
  r_multiple numeric(12,6),
  mfe_r numeric(12,6),
  mae_r numeric(12,6),
  exit_reason text,
  metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(metadata) = 'object'),
  created_at timestamptz not null default now()
);

create index paper_bot_equity_history_collected_idx on public.paper_bot_equity_history (bot_id, collected_at desc);
create index paper_bot_journal_bot_time_idx on public.paper_bot_journal (bot_id, occurred_at desc);
create index paper_bot_journal_symbol_time_idx on public.paper_bot_journal (bot_id, symbol, occurred_at desc) where symbol is not null;
create index paper_bot_journal_event_idx on public.paper_bot_journal (bot_id, event_type, occurred_at desc);

alter table public.paper_bot_ledgers enable row level security;
alter table public.paper_bot_equity_history enable row level security;
alter table public.paper_bot_positions enable row level security;
alter table public.paper_bot_journal enable row level security;
revoke all on public.paper_bot_ledgers, public.paper_bot_equity_history, public.paper_bot_positions, public.paper_bot_journal from public, anon, authenticated;
grant select, insert, update, delete on public.paper_bot_ledgers, public.paper_bot_equity_history, public.paper_bot_positions, public.paper_bot_journal to service_role;
grant usage, select on sequence public.paper_bot_journal_id_seq to service_role;

insert into public.paper_bot_ledgers (bot_id,display_name,status,strategy_id,strategy_version,starting_cash,cash,equity,realized_pl,unrealized_pl,peak_equity,source,metadata) values
('default-diverse','Default Diverse Bot','active','paper-medium-high-v1',1,1000,1000,1000,0,0,1000,'alpaca-paper','{"challenge":"$1,000 diversified paper challenge","brokerMapping":"temporary 1:1 until another bot is activated"}'::jsonb),
('penny-volatility-day-100','$100 Penny Volatility Day Bot','planned',null,null,100,100,100,0,0,100,'virtual','{"challenge":"higher-volatility intraday penny-stock experiment","executionEnabled":false}'::jsonb),
('three-trade-weekly-swing-100','$100 Three-Trade Weekly Swing Bot','planned',null,null,100,100,100,0,0,100,'virtual','{"challenge":"maximum three new swing entries per calendar week","executionEnabled":false}'::jsonb)
on conflict (bot_id) do nothing;

create or replace function public.paper_bot_sync_default_ledger(p_payload jsonb) returns void
language plpgsql security invoker set search_path = '' as $$
declare
  v_collected_at timestamptz;
  v_equity numeric;
  v_cash numeric;
  v_unrealized numeric := 0;
  v_peak numeric;
  v_positions jsonb;
begin
  if jsonb_typeof(p_payload) <> 'object' or jsonb_typeof(p_payload->'account') <> 'object' then raise exception 'Invalid bot ledger payload'; end if;
  v_collected_at := (p_payload->>'collectedAt')::timestamptz;
  v_equity := (p_payload->'account'->>'equity')::numeric;
  v_cash := nullif(p_payload->'account'->>'cash','')::numeric;
  v_positions := coalesce(p_payload->'positions', '[]'::jsonb);
  if v_equity < 0 then raise exception 'Invalid account equity'; end if;
  if jsonb_typeof(v_positions) not in ('array','null') then raise exception 'Invalid positions payload'; end if;
  if jsonb_typeof(v_positions) = 'array' then
    select coalesce(sum(coalesce((item->>'unrealizedPl')::numeric,0)),0) into v_unrealized from jsonb_array_elements(v_positions) item;
  end if;
  select greatest(peak_equity, v_equity) into v_peak from public.paper_bot_ledgers where bot_id='default-diverse' for update;
  if v_peak is null then raise exception 'Default Diverse ledger is not configured'; end if;
  update public.paper_bot_ledgers set cash=coalesce(v_cash,cash),equity=v_equity,unrealized_pl=v_unrealized,peak_equity=v_peak,
    current_drawdown_pct=case when v_peak>0 then least(0,(v_equity/v_peak-1)*100) else 0 end,
    last_synced_at=v_collected_at,updated_at=now(),source='alpaca-paper' where bot_id='default-diverse';
  insert into public.paper_bot_equity_history(bot_id,bucket_minute,collected_at,equity,cash,realized_pl,unrealized_pl)
  select 'default-diverse',date_trunc('minute',v_collected_at),v_collected_at,v_equity,v_cash,l.realized_pl,v_unrealized
  from public.paper_bot_ledgers l where l.bot_id='default-diverse'
  on conflict (bot_id,bucket_minute) do update set collected_at=excluded.collected_at,equity=excluded.equity,cash=excluded.cash,realized_pl=excluded.realized_pl,unrealized_pl=excluded.unrealized_pl;
  delete from public.paper_bot_positions where bot_id='default-diverse';
  if jsonb_typeof(v_positions)='array' then
    insert into public.paper_bot_positions(bot_id,symbol,asset_class,side,quantity,average_entry,market_value,unrealized_pl,strategy_id,strategy_version,updated_at,metadata)
    select 'default-diverse',left(item->>'symbol',32),'unknown',
      case when lower(coalesce(item->>'side','long')) in ('short','sell') then 'short' else 'long' end,
      coalesce(nullif(item->>'quantity','')::numeric,0),nullif(item->>'entry','')::numeric,
      nullif(item->>'marketValue','')::numeric,nullif(item->>'unrealizedPl','')::numeric,
      'paper-medium-high-v1',1,now(),'{"source":"alpaca-account-snapshot","attribution":"temporary 1:1"}'::jsonb
    from jsonb_array_elements(v_positions) item where coalesce(item->>'symbol','')<>'';
  end if;
end $$;

create or replace function public.paper_bot_record_journal(p_bot_id text,p_strategy_id text,p_strategy_version integer,p_event_type text,p_symbol text,p_asset_class text,p_payload jsonb) returns bigint
language plpgsql security invoker set search_path = '' as $$
declare v_id bigint;
begin
  if p_event_type not in ('candidate','rejected','authorized','submitted','filled','position_update','stop_update','partial_exit','closed','risk_event','system') then raise exception 'Invalid journal event'; end if;
  if jsonb_typeof(coalesce(p_payload,'{}'::jsonb)) <> 'object' then raise exception 'Invalid journal payload'; end if;
  insert into public.paper_bot_journal(bot_id,strategy_id,strategy_version,event_type,symbol,asset_class,occurred_at,score,qualification,regime,component_scores,market_snapshot,risk_plan,blockers,warnings,broker_order_id,client_order_id,entry_price,exit_price,quantity,realized_pl,r_multiple,mfe_r,mae_r,exit_reason,metadata)
  values (p_bot_id,p_strategy_id,p_strategy_version,p_event_type,nullif(p_symbol,''),nullif(p_asset_class,''),
    coalesce((p_payload->>'occurredAt')::timestamptz,now()),nullif(p_payload->>'score','')::numeric,
    nullif(p_payload->>'qualification',''),nullif(p_payload->>'regime',''),coalesce(p_payload->'componentScores','{}'::jsonb),
    coalesce(p_payload->'marketSnapshot','{}'::jsonb),coalesce(p_payload->'riskPlan','{}'::jsonb),
    coalesce(p_payload->'blockers','[]'::jsonb),coalesce(p_payload->'warnings','[]'::jsonb),
    nullif(p_payload->>'brokerOrderId',''),nullif(p_payload->>'clientOrderId',''),nullif(p_payload->>'entryPrice','')::numeric,
    nullif(p_payload->>'exitPrice','')::numeric,nullif(p_payload->>'quantity','')::numeric,nullif(p_payload->>'realizedPl','')::numeric,
    nullif(p_payload->>'rMultiple','')::numeric,nullif(p_payload->>'mfeR','')::numeric,nullif(p_payload->>'maeR','')::numeric,
    nullif(p_payload->>'exitReason',''),coalesce(p_payload->'metadata','{}'::jsonb))
  returning id into v_id;
  return v_id;
end $$;

revoke all on function public.paper_bot_sync_default_ledger(jsonb), public.paper_bot_record_journal(text,text,integer,text,text,text,jsonb) from public, anon, authenticated;
grant execute on function public.paper_bot_sync_default_ledger(jsonb), public.paper_bot_record_journal(text,text,integer,text,text,text,jsonb) to service_role;

create or replace function public.paper_report_save_snapshot(p_source_key text,p_payload jsonb) returns void
language plpgsql security invoker set search_path = '' as $$
declare v_collected_at timestamptz;
begin
  if p_source_key !~ '^[a-f0-9]{64}$' or jsonb_typeof(p_payload) <> 'object' then raise exception 'Invalid report payload'; end if;
  v_collected_at := (p_payload->>'collectedAt')::timestamptz;
  update public.paper_report_state set source_key=p_source_key,payload=p_payload,status='ready',last_attempt_at=now(),next_sync_at=now()+interval '20 seconds',lease_until=now(),message=null where report_key='main';
  insert into public.paper_report_history(source_key,bucket_minute,collected_at,equity)
  values (p_source_key,date_trunc('minute',v_collected_at),v_collected_at,(p_payload->'account'->>'equity')::numeric)
  on conflict (source_key,bucket_minute) do update set collected_at=excluded.collected_at,equity=excluded.equity;
  perform public.paper_bot_sync_default_ledger(p_payload);
end $$;
revoke all on function public.paper_report_save_snapshot(text,jsonb) from public, anon, authenticated;
grant execute on function public.paper_report_save_snapshot(text,jsonb) to service_role;
